// Regenerates the typed ABI modules in `src/chain/abis` from the compiled
// Foundry artifacts. The artifacts themselves are gitignored build output,
// so the generated modules are the committed source of truth for the server.
//
//   cd contracts && forge build
//   npm run abis:generate
//
// Never hand-edit the generated files — they get overwritten.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "chain", "abis");

const CONTRACTS = [
  { name: "PolicyRegistry", source: "PolicyRegistry.sol", file: "policyRegistry.ts", exportName: "policyRegistryAbi" },
  { name: "SpendGuard", source: "SpendGuard.sol", file: "spendGuard.ts", exportName: "spendGuardAbi" },
];

mkdirSync(outDir, { recursive: true });

for (const { name, source, file, exportName } of CONTRACTS) {
  const artifactPath = join(root, "contracts", "out", source, `${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));

  if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) {
    throw new Error(`${artifactPath} has no ABI — run \`forge build\` in contracts/ first.`);
  }

  const contents = `// AUTO-GENERATED by scripts/generate-abis.mjs — do not edit by hand.
// Source: contracts/out/${source}/${name}.json
// Regenerate with: npm run abis:generate (after \`forge build\` in contracts/)
export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  writeFileSync(join(outDir, file), contents);
  console.log(`wrote src/chain/abis/${file} (${artifact.abi.length} ABI entries)`);
}
